workflows:
  flutter-build:
    name: Flutter build workflow
    max_build_duration: 60
    instance_type: mac_mini
    trigger:
      branches:
        only:
          - master
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    ios:
      build:
        ipa:
          path: build/ios/ipa/Runner.ipa
