workflows:
  flutter-build:
    name: Flutter iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2  # Use Mac instances for iOS builds
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/Runner.ipa  # Path to save the generated .ipa file
    ios:
      # Specify the iOS build configurations
      distribution_method: ad-hoc  # or app-store for App Store deployment
      signing:
        identity: "Apple Distribution"  # Replace with your correct identity
        provisioning_profile: "ProvisioningProfileName"  # Replace with your provisioning profile name
