workflows:
  flutter:
    name: Flutter build workflow
    max_build_duration: 60
    instance_type: mac_mini
    platform: ios
    trigger:
      branches:
        only:
          - master
    ios:
      artifacts:
        - build/ios/ipa/Runner.ipa
