workflows:
  flutter-build:
    name: Flutter iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2  # Use Mac instances for iOS builds
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/Runner.ipa  # Path to save the generated .ipa file
